/* ============================================================================
   エティモリンゴ:レキシコピア・ファブル ― ゲーム効果データ
   ----------------------------------------------------------------------------
   言語学データ(etymon-explorer の pieData = words/roots)とは分離。
   ここには「ゲームでどう働くか」だけを書く。語義・発音・派生関係は
   実行時に語源データ側から 綴り(w)で引く。未登録語は起動時検証で落とす。
   ============================================================================ */
window.FABLE_DATA = {
  version: 1,

  /* ===== エティモン3体(加入は物語順で固定) ===== */
  etymons: [
    { id:'kaput-', name:'カプト', ja:'頭', img:'chara/T_ch_kaput_head.png', color:'#e8875a',
      hp:40, atk:7,
      intro:'われは カプト。「頭」の記憶。町にも 群れにも、先頭に立つ者が 要る。' },
    { id:'weid-', name:'ウェイド', ja:'見る・知る', img:'chara/T_ch_weid_see.png', color:'#a06ee0',
      hp:28, atk:6,
      intro:'ぼくは ウェイド。「見る」の記憶。見ることは、知ることだった。' },
    { id:'bhā-2', name:'ファーリ', ja:'話す', img:'chara/T_ch_bha_speak.png', color:'#f2a444',
      hp:30, atk:6,
      intro:'わたしは ファーリ。「話す」の記憶。ことばは、語られて はじめて 生きる。' },
  ],

  /* ===== 派生語(全40語)。role=一文で分かる役割 / areas=使える場所 /
         btl があれば戦闘の行動語。cost=復活に必要な語源記憶 ===== */
  words: [
    // --- *kaput- (13) ---
    { w:'captain', root:'kaput-', areas:['expedition'], cost:3,
      role:'遠征隊を率いる', btl:null, revive:'船乗り帽の隊長が 遠征本部に着任した' },
    { w:'chef', root:'kaput-', areas:['kitchen'], cost:3,
      role:'食材を料理へ加工する', revive:'コック帽の料理人が 厨房に住み着いた' },
    { w:'chief', root:'kaput-', areas:['plaza','town'], cost:3,
      role:'町の仕事を管理する(町イベントが起きる)', revive:'長(おさ)が 広場で 采配をはじめた' },
    { w:'chapter', root:'kaput-', areas:['library'], cost:2,
      role:'遠征の出来事を章として保存する', revive:'図書館に「章」の棚が生まれた' },
    { w:'capital', root:'kaput-', areas:['market'], cost:3,
      role:'市場で資源を売り買いする', revive:'市場に元手(もとで)が生まれ、交換ができる' },
    { w:'cattle', root:'kaput-', areas:['farm'], cost:2,
      role:'牛を飼い、ミルクを得る', revive:'牧舎に牛がもどってきた' },
    { w:'head', root:'kaput-', areas:['tree'], cost:2,
      role:'一族の頭。復元のようすを見守る', revive:'アルファベット樹に「頭」の紋が灯った' },
    { w:'headquarters', root:'kaput-', areas:['expedition'], cost:3,
      role:'遠征の本部を置く(遠征所が開く)', revive:'遠征本部の建物が建った' },
    { w:'achievement', root:'kaput-', areas:['library'], cost:2,
      role:'町の実績を記録する', revive:'図書館に実績帳が置かれた' },
    { w:'cadet', root:'kaput-', areas:['expedition'], cost:2,
      role:'見習い隊員。遠征の荷物が1つ増える', revive:'見習いの子が本部に駆け込んできた' },
    { w:'biceps', root:'kaput-', areas:['town'], cost:2,
      role:'力仕事を手伝う(木材・石材の採集+1)', revive:'força! 力じまんが手伝いに来た' },
    { w:'heading', root:'kaput-', areas:['library'], cost:1,
      role:'記録に見出しを付けて探しやすくする', revive:'本棚に見出しが付いた' },
    { w:'ahead', root:'kaput-', areas:['expedition'], cost:1,
      role:'一歩先へ。遠征の移動が少し速い', revive:'隊の歩みが軽くなった' },
    // --- *weid- (14) ---
    { w:'view', root:'weid-', areas:['observatory'], cost:2,
      role:'遠征先の様子を見る(地形が事前に分かる)', revive:'観測台から遠くが見えるようになった' },
    { w:'vision', root:'weid-', areas:['observatory','battle'], cost:3,
      role:'危険や敵の情報を見る', btl:{ ja:'弱点をあばく', fx:'expose' },
      revive:'観測台に「視」のレンズが入った' },
    { w:'guide', root:'weid-', areas:['expedition','battle'], cost:3,
      role:'道や目的地を案内する', btl:{ ja:'にげ道を案内(確実に逃走)', fx:'escape' },
      revive:'旅なれた案内人が本部に加わった' },
    { w:'wise', root:'weid-', areas:['plaza','library'], cost:2,
      role:'賢者として助言する(町イベントの選択肢が増える)', revive:'物知りの賢者が広場に座った' },
    { w:'wizard', root:'weid-', areas:['plaza'], cost:3,
      role:'知恵の技を披露する(名声+)', revive:'魔法使いが広場で拍手を浴びた' },
    { w:'video', root:'weid-', areas:['library','observatory','plaza'], cost:3,
      role:'映像を記録・再生・上映する', revive:'記録所に映写機が置かれた' },
    { w:'idea', root:'weid-', areas:['library','kitchen'], cost:2,
      role:'ひらめきを書き留める(新しい料理の着想)', revive:'アイデア帳が生まれた' },
    { w:'idol', root:'weid-', areas:['plaza'], cost:2,
      role:'みんなの偶像。広場の人気者になる(名声+)', revive:'広場にアイドルが立った' },
    { w:'history', root:'weid-', areas:['library'], cost:2,
      role:'町の歴史をまとめる', revive:'図書館に歴史の棚ができた' },
    { w:'story', root:'weid-', areas:['library','plaza'], cost:2,
      role:'見て知ったことを物語として残す', revive:'物語の棚ができた' },
    { w:'evidence', root:'weid-', areas:['observatory'], cost:2,
      role:'見た証拠を記録する(観測の確度が上がる)', revive:'観測記録が正式なものになった' },
    { w:'review', root:'weid-', areas:['library'], cost:1,
      role:'記録を見直す(語源記憶が少し増える)', revive:'見直しの習慣が生まれた' },
    { w:'survey', root:'weid-', areas:['observatory','expedition'], cost:2,
      role:'上から見渡して調査する(遠征マップが開く)', revive:'測量の道具が観測台に届いた' },
    { w:'interview', root:'weid-', areas:['plaza'], cost:1,
      role:'訪問者に会って見聞きする(名声+)', revive:'広場で会見が開かれた' },
    // --- *bhā-2 (13) ---
    { w:'fable', root:'bhā-2', areas:['library','plaza','battle'], cost:2,
      role:'物語を聞かせる', btl:{ ja:'物語を聞かせて眠らせる', fx:'sleep' },
      revive:'語り部の火が広場に灯った' },
    { w:'fame', root:'bhā-2', areas:['plaza'], cost:3,
      role:'町の評判が広まり、訪問者が増える', revive:'町の名が外へ語られはじめた' },
    { w:'confess', root:'bhā-2', areas:['plaza'], cost:2,
      role:'打ち明け話の場をひらく(町イベント)', revive:'広場に告白の椅子が置かれた' },
    { w:'prophecy', root:'bhā-2', areas:['observatory','battle'], cost:3,
      role:'次の出来事の兆候を語る', btl:{ ja:'敵の次の次まで先読み', fx:'foresee' },
      revive:'観測台に予言の書見台が付いた' },
    { w:'prophet', root:'bhā-2', areas:['observatory'], cost:3,
      role:'前もって語る人。観測台に立つ', revive:'預言者が観測台に登った' },
    { w:'symphony', root:'bhā-2', areas:['plaza','battle'], cost:3,
      role:'音楽を演奏する', btl:{ ja:'演奏でみんなの気合+', fx:'rally' },
      revive:'広場に楽団の音合わせが響いた' },
    { w:'phone', root:'bhā-2', areas:['expedition','town'], cost:2,
      role:'遠くの声を届ける(遠征先から町に連絡)', revive:'声の糸が町と野をつないだ' },
    { w:'telephone', root:'bhā-2', areas:['town'], cost:3,
      role:'町の通信柱。連絡が早くなる', revive:'通信柱が広場のすみに立った' },
    { w:'infant', root:'bhā-2', areas:['town'], cost:2,
      role:'まだ話せない子。町に赤ちゃんが生まれる', revive:'町に元気な泣き声がひびいた' },
    { w:'famous', root:'bhā-2', areas:['plaza'], cost:2,
      role:'よく語られる評判(名声+)', revive:'旅人が町のうわさを持ち帰った' },
    { w:'fate', root:'bhā-2', areas:['observatory'], cost:2,
      role:'語られた運命。兆しを読む', revive:'運命の言葉が書き留められた' },
    { w:'fairy', root:'bhā-2', areas:['plaza'], cost:2,
      role:'語られる妖精。祭りに現れる', revive:'祭りの夜に小さな灯りが舞った' },
    { w:'bee', root:'bhā-2', areas:['farm'], cost:2,
      role:'みつばちを飼い、はちみつを得る', revive:'みつばち箱がぶんぶん鳴りだした' },
  ],

  /* ===== 建物・設備(15+)。unlock: 条件(word=その語の復活で開く) ===== */
  buildings: [
    { id:'tree', name:'アルファベット樹', area:'tree', x:955, y:300, w:230, always:1,
      desc:'エティモンと英単語の復活の中心' },
    { id:'farm', name:'牧場', area:'farm', x:290, y:600, w:200, word:'cattle', desc:'牛やみつばちを飼う' },
    { id:'barn', name:'牧舎', area:'farm', x:180, y:520, w:130, word:'cattle', deco:1 },
    { id:'hive', name:'みつばち箱', area:'farm', x:430, y:660, w:90, word:'bee', deco:1 },
    { id:'kitchen', name:'厨房', area:'kitchen', x:640, y:640, w:170, word:'chef', desc:'食材を料理にする' },
    { id:'oven', name:'かまど', area:'kitchen', x:730, y:700, w:90, word:'chef', deco:1 },
    { id:'hq', name:'遠征本部', area:'expedition', x:1560, y:600, w:200, word:'captain', desc:'遠征隊を編成して出発する' },
    { id:'watch', name:'見張り台', area:'expedition', x:1680, y:500, w:110, word:'headquarters', deco:1 },
    { id:'library', name:'図書館', area:'library', x:1240, y:640, w:180, word:'chapter', desc:'章・物語・映像を保存する' },
    { id:'shelf', name:'記録棚', area:'library', x:1330, y:700, w:90, word:'heading', deco:1 },
    { id:'observatory', name:'観測台', area:'observatory', x:1450, y:330, w:150, word:'view', desc:'遠くと先を見る' },
    { id:'plaza', name:'広場の舞台', area:'plaza', x:930, y:700, w:220, word:'chief', desc:'物語・音楽・にぎわいの場' },
    { id:'market', name:'市場', area:'market', x:520, y:770, w:180, word:'capital', desc:'資源を売り買いする' },
    { id:'phonepole', name:'通信柱', area:'town', x:1120, y:560, w:70, word:'telephone', deco:1 },
    { id:'nursery', name:'ゆりかごの家', area:'town', x:800, y:540, w:120, word:'infant', deco:1 },
    { id:'idolstage', name:'アイドルの台', area:'plaza', x:1040, y:740, w:80, word:'idol', deco:1 },
  ],

  /* ===== 生産・加工(5種) ===== */
  production: [
    { id:'milk', name:'ミルクしぼり', area:'farm', need:'cattle', grow:40, out:{food:2}, ja:'牛のミルクをしぼる(食料+2)' },
    { id:'honey', name:'はちみつ集め', area:'farm', need:'bee', grow:60, out:{food:3}, ja:'はちみつを集める(食料+3)' },
    { id:'wood', name:'木こり', area:'town', need:null, grow:35, out:{wood:2}, ja:'町はずれで木を切る(木材+2)' },
    { id:'stone', name:'石ひろい', area:'town', need:null, grow:45, out:{stone:2}, ja:'川原で石をひろう(石材+2)' },
    { id:'cook', name:'料理', area:'kitchen', need:'chef', grow:20, cost:{food:3}, out:{meal:1}, ja:'食料3→遠征用の食事1(chefが加工)' },
  ],

  /* ===== 遠征3地域。nodes: b=戦闘 r=資源 m=単語の記憶 e=イベント s=休息 B=ボス ===== */
  regions: [
    { id:'forest', name:'序盤の森', bg:'ground/T_BG_base_ground_tree.png', open:1,
      nodes:['b','r','e','m','b','e','s','B'], boss:'jab_moss',
      enemies:['mosshound','thornrat','logcrab','mistmoth'],
      loot:{wood:3, mem:3}, ja:'ジャバウォックの霧が浅い、はじまりの森' },
    { id:'city', name:'崩壊した都市', bg:'ground/T_BG_base_ruin.png', openAfter:'forest',
      nodes:['b','e','r','m','b','e','r','s','b','B'], boss:'jab_silence',
      enemies:['rustgolem','shadowcat','glasscrow','inkslime'],
      loot:{stone:3, mem:4}, ja:'ことばを失った都市の廃墟' },
    { id:'coast', name:'海岸', bg:'ground/T_BG_base_sea.png', openAfter:'city',
      nodes:['e','b','r','m','b','e','m','s','b','B'], boss:'jab_deep',
      enemies:['saltcrab','foghorn','wrecktopus','tidewisp'],
      loot:{mem:5, food:3}, ja:'霧の向こうに何かが見える海辺' },
  ],

  /* ===== 敵12種+ボス3体。weak: 語根(その一族の行動語/攻撃が2倍) ===== */
  enemies: [
    { id:'mosshound', name:'こけまみれの犬', hp:16, atk:4, weak:'kaput-', tell:'とびかかろうと 身をかがめた' },
    { id:'thornrat', name:'とげねずみ', hp:12, atk:3, weak:'weid-', tell:'茂みに 隠れようとしている' },
    { id:'logcrab', name:'丸太ガニ', hp:20, atk:5, weak:'kaput-', tell:'はさみを ふりかぶった' },
    { id:'mistmoth', name:'霧の蛾', hp:14, atk:4, weak:'weid-', tell:'りんぷんを まき散らそうとしている' },
    { id:'rustgolem', name:'さびゴーレム', hp:26, atk:6, weak:'kaput-', tell:'腕を 大きく 振り上げた' },
    { id:'shadowcat', name:'影のねこ', hp:18, atk:5, weak:'weid-', tell:'影に とけこもうとしている' },
    { id:'glasscrow', name:'ガラスからす', hp:16, atk:6, weak:'bhā-2', tell:'甲高く 鳴こうとしている' },
    { id:'inkslime', name:'インクスライム', hp:22, atk:5, weak:'bhā-2', tell:'文字を 溶かそうと にじり寄る' },
    { id:'saltcrab', name:'しおガニ', hp:24, atk:6, weak:'kaput-', tell:'泡を ふきはじめた' },
    { id:'foghorn', name:'霧笛のぬけがら', hp:20, atk:7, weak:'bhā-2', tell:'ぼうっと 鳴る 構えだ' },
    { id:'wrecktopus', name:'難破だこ', hp:28, atk:7, weak:'weid-', tell:'足を 八本 ひろげた' },
    { id:'tidewisp', name:'しおの精', hp:18, atk:6, weak:'bhā-2', tell:'波の音に 声をかくしている' },
    { id:'jab_moss', name:'ジャバの森喰い', boss:1, hp:40, atk:7, weak:'kaput-',
      tell:'森ぜんぶを のみこもうと 口を開けた', drop:{mem:6} },
    { id:'jab_silence', name:'ジャバの沈黙', boss:1, hp:56, atk:9, weak:'bhā-2',
      tell:'あたりの音を すいこんでいる', drop:{mem:8} },
    { id:'jab_deep', name:'ジャバの深潮', boss:1, hp:66, atk:10, weak:'weid-',
      tell:'海霧のおくで 目が ひかった', drop:{mem:10} },
  ],

  /* ===== 遠征イベント(20+)。ch: 選択肢 [文, 効果] ===== */
  events: [
    { t:'たおれた道しるべを 見つけた。', ch:[['起こして directions を読む(語源記憶+1)',{mem:1}],['先を急ぐ',{}]] },
    { t:'甘いにおいの 実がなっている。', ch:[['もいで持ち帰る(食料+2)',{food:2}],['鳥のために残す(名声+1)',{rep:1}]] },
    { t:'こわれた小屋に 板が散らばっている。', ch:[['板を回収する(木材+2)',{wood:2}],['小屋を直しておく(名声+1)',{rep:1}]] },
    { t:'白い石が 川原に光る。', ch:[['ひろう(石材+2)',{stone:2}],['積んで道しるべにする(名声+1)',{rep:1}]] },
    { t:'古い日記の切れはしが 落ちている。', ch:[['読む(語源記憶+2)',{mem:2}],['そっと戻す',{}]] },
    { t:'迷子のこどもの声がする。', ch:[['声のほうへ案内する(名声+2)',{rep:2}],['気のせいだ…',{}]] },
    { t:'湧き水を 見つけた。', ch:[['隊を休ませる(全員のきずが少し回復)',{heal:6}],['水筒に入れて先へ',{food:1}]] },
    { t:'霧の中に 大きな影。回り道する?', ch:[['回り道(安全)',{}],['つっきる(食料-1で時短)',{food:-1}]] },
    { t:'空きびんに 手紙が入っている。', ch:[['読む(語源記憶+1)',{mem:1}],['流す(名声+1)',{rep:1}]] },
    { t:'倒木が道をふさぐ。', ch:[['押しのける(木材+1)',{wood:1}],['くぐる',{}]] },
    { t:'こわれた時計台の部品が光る。', ch:[['部品を拾う(石材+1,語源記憶+1)',{stone:1,mem:1}],['触らない',{}]] },
    { t:'看板の文字が消えかけている。', ch:[['なぞって書き足す(語源記憶+1,名声+1)',{mem:1,rep:1}],['通り過ぎる',{}]] },
    { t:'ちいさな祠に supplies が供えてある。', ch:[['ありがたく頂く(食料+2)',{food:2}],['手を合わせるだけ(名声+1)',{rep:1}]] },
    { t:'雨やどりの洞穴を見つけた。', ch:[['ひと休み(きず回復)',{heal:5}],['雨の中を進む',{}]] },
    { t:'棚に缶詰が残っている。', ch:[['持ち帰る(食料+3)',{food:3}],['次の旅人に残す(名声+2)',{rep:2}]] },
    { t:'ガラス片がきらめく坂道。', ch:[['慎重に進む',{}],['駆け抜ける(きず-3, 時短)',{heal:-3}]] },
    { t:'流れ着いた木箱がある。', ch:[['開ける(木材+2)',{wood:2}],['海に返す',{}]] },
    { t:'砂浜に大きな文字が書かれている。', ch:[['読み解く(語源記憶+2)',{mem:2}],['波に消える前に写す(語源記憶+1,名声+1)',{mem:1,rep:1}]] },
    { t:'灯台の階段が 続いている。', ch:[['のぼって見渡す(次の道が分かる)',{scout:1}],['下で待つ',{}]] },
    { t:'ひとりぼっちのカモメが ついてくる。', ch:[['パンくずをやる(食料-1,名声+2)',{food:-1,rep:2}],['ほうっておく',{}]] },
    { t:'折れた旗ざおに 旗がからまる。', ch:[['立て直す(名声+2)',{rep:2}],['旗だけ回収(木材+1)',{wood:1}]] },
    { t:'岩のすき間で 何かが鳴いている。', ch:[['助け出す(名声+2)',{rep:2}],['そっとする',{}]] },
  ],

  /* ===== 町イベント(10+)。need: 必要な復活語(無ければ選択肢が減る) ===== */
  townEvents: [
    { t:'旅の商人が来た。「木材5と食料3、交換しない?」', need:null,
      ch:[['交換する',{wood:-5,food:3}],['ことわる',{}]] },
    { t:'こどもたちが「おはなし聞きたい!」と集まった。', need:'fable',
      ch:[['fable を語る(名声+2)',{rep:2,useWord:'fable'}],['また今度ね',{}]] },
    { t:'夕暮れの広場に人が集まっている。', need:'symphony',
      ch:[['symphony を演奏する(名声+3)',{rep:3,useWord:'symphony'}],['静かな夜にする',{}]] },
    { t:'誰かが「打ち明けたいことがある」と言う。', need:'confess',
      ch:[['confess の椅子をすすめる(名声+2)',{rep:2,useWord:'confess'}],['そっと見守る',{}]] },
    { t:'牛が柵を越えそうだ!', need:'cattle',
      ch:[['みんなで連れ戻す(食料+1)',{food:1,useWord:'cattle'}],['chief に任せる(名声+1)',{rep:1,useWord:'chief'}]] },
    { t:'保存食が少し傷んでいた…', need:null,
      ch:[['早めに食べる(食料-2)',{food:-2}],['chef が煮直す(食料-1)',{food:-1,useWord:'chef'}]] },
    { t:'雨上がりの空に大きな虹!', need:'video',
      ch:[['video で記録する(名声+2)',{rep:2,useWord:'video'}],['みんなで眺める(名声+1)',{rep:1}]] },
    { t:'旅人が町の評判をたずねてきた。', need:'famous',
      ch:[['famous な話をする(名声+2)',{rep:2,useWord:'famous'}],['お茶を出すだけ',{rep:1}]] },
    { t:'図書館の棚がいっぱいになってきた。', need:'heading',
      ch:[['heading で整理(語源記憶+1)',{mem:1,useWord:'heading'}],['そのままにする',{}]] },
    { t:'夜、こわい夢を見たという子がいる。', need:'wise',
      ch:[['wise の賢者が話を聞く(名声+2)',{rep:2,useWord:'wise'}],['あたたかいミルクを出す(食料-1,名声+1)',{food:-1,rep:1}]] },
    { t:'祭りの夜、小さな灯りが舞った…!', need:'fairy',
      ch:[['fairy の話を語り継ぐ(名声+2,語源記憶+1)',{rep:2,mem:1,useWord:'fairy'}],['夢だったのかも',{}]] },
    { t:'赤ちゃんが初めて「ばー」と言った!', need:'infant',
      ch:[['みんなでお祝い(名声+2)',{rep:2,useWord:'infant'}],['記録にのこす(語源記憶+1)',{mem:1}]] },
  ],

  /* ===== 復元段階(エティモンごと)。n=その一族の語を「実際に使った」種類数 ===== */
  stages: [
    { n:1, ja:'目ざめ' }, { n:3, ja:'思い出す' }, { n:5, ja:'力強く' }, { n:8, ja:'全盛' },
  ],

  /* ===== 序章〜進行(加入・開放はデータで変更しやすく) ===== */
  script: {
    prologue: [
      '――ことばが、こわれた。',
      '言語崩壊《ジャバウォック》。英単語は意味を失い、それが支えていた文明も 霧に沈んだ。',
      'ここは 生きのこった小さな町、レキシコピア。',
      '町はずれの「アルファベット樹」に、最初の記憶が ねむっている――',
    ],
    joins: [
      { etymon:'kaput-', when:'start',   line:'樹の根もとで、最初のエティモンが 目をさました。' },
      { etymon:'weid-',  when:'forest',  line:'森のおくの遺跡で、「見る」の記憶が 目をさました。' },
      { etymon:'bhā-2',  when:'city',    line:'都市の図書館あとで、「話す」の記憶が 目をさました。' },
    ],
    firstWords: ['chef','captain','chief'],   // 最初の復活候補(かならず3択)
  },
};
